#!/usr/bin/env bash

# -- Intro
# Created by jordantrizz v0.1
# 

# -- Variable Ingestion

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -s|--script)
    SCRIPT="$2"
    shift # past argument
    shift # past value
    ;;
    -c|--command)
    COMMAND="$2"
    shift # past argument
    shift # past value
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

if [[ -n $1 ]]; then
    echo "Last line of file specified as non-opt/last argument:"
    tail -1 "$1"
fi

# -- Variables
gp_api_url="https://my.gridpane.com/oauth/api/v1/$gp_api_endpoint"
gp_api_token=.gptoken
gp_api_cmd=$(curl -s $gp_api_url --header 'Authorization: Bearer $gp_api_access_token')

## - Color
RED='\033[97;41m'
GREEN='\033[97;42m'
NC='\033[0m' # No Color
SUCCESS="${GREEN}* SUCCESS *${NC}"
ERROR="${RED}* ERROR *${NC}"

# -- Functions
check_gptoken () {

	if [ -f "$gp_api_token" ]; then
		echo -e "$SUCCESS GP Token file found $gp_api_access_token"
	else
		echo -e "$ERROR GP Token file missing, please place your GridPane API Token in the file named .gptoken"
	fi

}

help () {

}

check_variables () {
	
}

send_command () {
}

# -- Variable Ingestion

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -e|--extension)
    EXTENSION="$2"
    shift # past argument
    shift # past value
    ;;
    -s|--searchpath)
    SEARCHPATH="$2"
    shift # past argument
    shift # past value
    ;;
    -l|--lib)
    LIBPATH="$2"
    shift # past argument
    shift # past value
    ;;
    --default)
    DEFAULT=YES
    shift # past argument
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

echo "FILE EXTENSION  = ${EXTENSION}"
echo "SEARCH PATH     = ${SEARCHPATH}"
echo "LIBRARY PATH    = ${LIBPATH}"
echo "DEFAULT         = ${DEFAULT}"
echo "Number files in SEARCH PATH with EXTENSION:" $(ls -1 "${SEARCHPATH}"/*."${EXTENSION}" | wc -l)
if [[ -n $1 ]]; then
    echo "Last line of file specified as non-opt/last argument:"
    tail -1 "$1"
fi

# -- Init
check_gptoken
